### ISSUE TITLE
Error: Unrecognized document structure: {"colSpan":1,"rowSpan":8,"qr":"","fit":120}

### ISSUE THREAD

**Issue by saraidev** [nodecfdi/cfdi-to-pdf#3]
Hola, estoy tratando de transformar mi contenido xml(cfdi) a PDF, sin embargo me sale este error. 

Unrecognized document structure: {"colSpan":1,"rowSpan":8,"qr":"","fit":120}

Estoy implementandolo en nodejs de la siguiente manera:

const xml = 'contendio xml';
        const comprobante = XmlNodeUtils.nodeFromXmlString(xml);
        const cfdiData = new CfdiData(comprobante, '', 'cadenaOrigen', 'myLogoImageBase64');
        const builder = new PdfMakerBuilder(new GenericCfdiTranslator());
        await builder.build(cfdiData, uploadPath);

Y justo en el último paso, cuando llamo a "build", me aparece el error. 
Importe los archivos de la siguiente manera, ya que no estoy programando en typescript
const {
    GenericCfdiTranslator,
    PdfMakerBrowserBuilder,
    PdfMakerBuilder,
    CfdiData,
}= require('@nodecfdi/cfdi-to-pdf');
const {XmlNodeUtils}=require('@nodecfdi/cfdiutils-common');

**Comment by luffynando** [comment]
Que versión actualmente estas probando? La ultima versión es la que admite un valor vacio en el codigo qr, versiones anteriores no permiten mandar vacio ese parametro

**Comment by luffynando** [comment]
"La secuencia de datos formada con la información contenida dentro de la factura electrónica, establecida en el Rubro C del Anexo 20 de la Resolución Miscelánea Fiscal.

Ejemplo
```text
||3.3|FTVN|41|2017-08-14T00:00:00|01|30001000000300023699|10000|0|JPY|0.166123|11600|I|PUE|45070|EKU9003173C9|ESCUELA KEMPER URGATE SA DE CV|601|KAHO641101B39|OSCAR KALA HAAK|G01|25101800|23534855|1|EA|PZA|Concepto con divisa JPY|10000|10000|10000|002|Tasa|0.160000|1600|0|002|Tasa|0.160000|1600|1600||
```

**Comment by luffynando** [comment]
Lamentablemente en la libreria actual no puedo generarla automaticamente, por lo que en su proceso o aplicación tendran que generarla y pasarla a la instancia de esta libreria. Se genera utilizando el xsd correspondiente ya sea cfdi33, cfdi40, etc utilizando un xslt transform

**Comment by luffynando** [comment]
Puedes usar @nodecfdi/cfdiutils-core para generar la cadena origen https://nodecfdi.github.io/cfdiutils-core/classes/TfdCadenaDeOrigen.html
